{"name": "Reject request for existing card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[contains(text(),'Reject')]\"}\n  (Session info: chrome=88.0.4324.146)\n\n", "trace": "  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\rejectrequeststeps.py\", line 92, in step_impl\n    context.driver.find_element_by_xpath(rejectec_button_xpath).send_keys(\"Invalid Request\")\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user search for EZ-Link's Portal", "status": "passed", "start": 1612855096643, "stop": 1612855102272}, {"name": "When he enter login credentials", "status": "passed", "start": 1612855102272, "stop": 1612855102695}, {"name": "Then he should be able to access View All Top Up Requests page", "status": "passed", "start": 1612855102696, "stop": 1612855103323}, {"name": "Given the user click the filter results for the job order number of existing card", "status": "passed", "start": 1612855103327, "stop": 1612855122462}, {"name": "When he check top-up request information", "status": "passed", "start": 1612855122463, "stop": 1612855122636}, {"name": "And reject the request with proper reason", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//button[contains(text(),'Reject')]\"}\n  (Session info: chrome=88.0.4324.146)\n\n", "trace": "  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\rejectrequeststeps.py\", line 92, in step_impl\n    context.driver.find_element_by_xpath(rejectec_button_xpath).send_keys(\"Invalid Request\")\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\lukegoh\\desktop\\python projects\\automationtesting\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1612855122637, "stop": 1612855132698}, {"name": "Then submission will be successful", "status": "skipped", "start": 1612855132700, "stop": 1612855132700}, {"name": "And status will show \"Returned\" when user search for the job order number of existing card entered in the filter textbox", "status": "skipped", "start": 1612855132700, "stop": 1612855132700}], "start": 1612855096641, "stop": 1612855132700, "uuid": "e83b5b39-2b3e-45a2-83fa-18ce6d78d9d5", "historyId": "0f8e7e282483480eb07e42e0aef5cecc", "fullName": "Rejection of top up requests: Reject request for existing card", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Rejection of top up requests"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}